steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push

  - name : gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/yoramyoram-nestjs
      - yoramyoram-sha256-1=asia.gcr.io/yoramyoram-373201/yoramyoram:0.4
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUD_CONTAINER_CLUSTER=autopilot-cluster-1